apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-new-app
  labels:
    app: aks-new-app
    namespace: dev
spec:
  selector:
    matchLabels:
      app: aks-new-app
  template:
    metadata:
      labels:
        app: aks-new-app
    spec:
      containers:
      - name: aks-new-app
        image: abidh786/akspurpose-repo:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"  

        
---
apiVersion: v1
kind: Service
metadata:
  name: aks-new-service
  labels:
    app: aks-new-app
    namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: aks-new-app
  ports:
  - port: 8080
    targetPort: 8080



       
