apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-serviceaccount
  namespace: dev
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: pod-reader
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["ingress"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: dev
roleRef: # points to my Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader # name of role
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: my-serviceaccount # service account to bind to
  namespace: dev # ns of service account      