# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: salman-terraform
  vmImage: Agent-0777

variables:
  tag: $(Build.BuildId)



stages: 
  - stage: creatingdockerimage
    jobs:
      - job: 
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker_Custom'
            command: 'login'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker build -t newimage123:latest .
              
              docker build -t newimage123:$(tag) .
              
              docker tag newimage123:latest abidh786/httpd-image:latest
              
              docker tag newimage123:latest abidh786/httpd-image:$(tag)
  - stage: pushingdemo
    jobs:
      - job:  
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'Hello world'
              
              echo '$(tag)'
              docker push abidh786/httpd-image:$(tag)
  - stage: copyandpublishartificats
    jobs:
      - job: 
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '**/*.yaml'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            
                     
        
                 
          
            
       
    
    



    
     

    

