# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
    - group: myvariablesgroup
    
  

pool:
 name: new-agent
 vmimage: salman-007

stages:
    - stage: login_into_docker
      jobs:
          - job: 
            steps:
              - task: CmdLine@2
                displayName: docker_login
                inputs:
                  script: 'echo $(Dockerpassword) | docker login --username $(DockerUsername) --password-stdin'

    - stage: build_docker_image
      jobs:
        - job: 
          steps:
          - task: Bash@3
            displayName: docker-image-build
            inputs:
              targetType: 'inline'
              script: |
                cd aks-purpose-project/
                docker build -t $(Docker-repo-master):latest .
                docker build -t $(Docker-repo-master):$(Build.BuildId) .
                docker tag $(Docker-repo-master):latest abidh786/$(Docker-repo-master):latest
                docker tag $(Docker-repo-master):$(Build.BuildId) abidh786/$(Docker-repo-master):$(Build.BuildId)
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                cd eks-purpose-project
                docker build -t $(Dockereks-repo):latest .
                docker build -t $(Dockereks-repo):$(Build.BuildId) .
                docker tag $(Dockereks-repo):latest abidh786/$(Dockereks-repo):latest
                docker tag $(Dockereks-repo):$(Build.BuildId) abidh786/$(Dockereks-repo):$(Build.BuildId)

    - stage: push_docker_image
      jobs:
        - job:
          steps:
          - task: Bash@3
            displayName: push_docker_image
            inputs:
              targetType: 'inline'
              script: |
                docker push abidh786/$(Docker-repo-master):latest
                docker push abidh786/$(Docker-repo-master):$(Build.BuildId)
                docker push abidh786/$(Dockereks-repo):latest
                docker push abidh786/$(Dockereks-repo):$(Build.BuildId)

    - stage: copy_publish_artifcats
      jobs:
        - job:
          steps:
            - task: CopyFiles@2
              displayName: copy_publish_artificats
              inputs:
                SourceFolder: '$(System.DefaultWorkingDirectory)'
                Contents: 'kuberenetes/*.yml'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'

    - stage: awskmsgetkey
      jobs:
        - job:
          steps:
            -  task: SecretsManagerGetSecret@1
               inputs:
                 awsCredentials: 'AWS_Service'
                 regionName: 'ap-south-1'
                 secretIdOrName:  'arn:aws:kms:ap-south-1:810901317241:key/ffea522d-6b13-4478-985b-9b50c28644c3'
                 variableName: 'myvar'


                                        


  
