# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
    - group: myvariablesgroup
    
  

pool:
 name: new-agent
 vmimage: salman-007

stages:
    - stage: login_into_docker
      jobs:
          - job: 
            steps:
              - task: CmdLine@2
                displayName: docker_login
                inputs:
                  script: 'echo $(Dockerpassword) | docker login --username $(DockerUsername) --password-stdin'


  
