# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
   name: salman-devops
   password: salman
   location: hyderabad
    
  

pool:
 name: new-agent
 vmimage: salman-007
    

steps:
- script: |
    echo myvariables-$(name)
    echo myvariables-$(password)
    echo myvariables-$(location)
    


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
