# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature

pool:
  name: Salman-PC
  vmImage: Agent-0777

variables:
- group: AWS_ECR

steps:
- task: Docker@2
  displayName: 'Building a docker image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    repository: '$(AWS_ECR_IMAGE_URL)'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS_Service'
    regionName: 'ap-south-1'
    imageSource: 'imagename'
    sourceImageName: '$(AWS_ECR_IMAGE_URL)'
    sourceImageTag: '$(Build.BuildId)'
    pushTag: latest
    repositoryName: '$(AWS_ECR_IMAGE_URL)'
    
     

    

