# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - feature
 paths:
   include:
     - aks-purpose-project/*
     - eks-purpose-project/*  
variables:
    - name: COSIGN_PASSWORD
      value: 'Salman@789'
    
  

pool:
 name: eks-agent
 vmimage: newtestinghosted

stages:
    - stage: npm_install_artificats
      jobs:
        - job:
          steps:
           - task: Bash@3
             inputs:
               targetType: 'inline'
               script: yes y | cosign sign --key /root/cosign.key abidh786/akspurpose-repo-master:latest

          
              
                  


          




                                        


  
