# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
    - group: myvariablesgroup
    
  

pool:
 name: npm-testing
 vmimage: npmagent

stages:
    - stage: npm_install_artificats
      jobs:
        - job:
          steps:
          - task: Npm@1
            inputs:
              command: 'install'
           

    

    - stage: copy_publish_artifcats
      jobs:
        - job:
          steps:
            - task: CopyFiles@2
              displayName: copy_publish_artificats
              inputs:
                SourceFolder: '$(System.DefaultWorkingDirectory)'
                Contents: 'kuberenetes/*.yml'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'
          
              
                  


          




                                        


  
