# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
    - group: myvariablesgroup
    
  

pool:
 name: new-agent
 vmimage: salman-007

stages:
    - stage: login_into_docker
      jobs:
          - job: 
            steps:
              - task: CmdLine@2
                displayName: docker_login
                inputs:
                  script: 'echo $(Dockerpassword) | docker login --username $(DockerUsername) --password-stdin'

    - stage: build_docker_image
      jobs:
        - job: 
          steps:
          - task: Bash@3
            displayName: docker-image-build
            inputs:
              targetType: 'inline'
              script: |
                cd aks-purpose-project/
                docker build -t akspurpose-repo:latest .
                docker tag akspurpose-repo:latest abidh786/akspurpose-repo:latest
                                        


  
