# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature
parameters:
  - name: clean
    displayName: cleaning the code
    type: boolean
    default: true
    values:
      - true
      - false


pool:
  name: new-agent
  vmImage: salman-007

steps:
- checkout: clean
  clean: ${{ parameters.clean }}
  

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
