# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: salman-terraform
  vmImage: Agent-0777

variables:
  tag: $(Build.BuildId)



stages: 
  - stage: creatingdockerimage
    jobs:
      - job: 
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker_Custom'
            command: 'login'
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker_Custom'
            repository: 'httpd-image'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: $(tag)
  - stage: pushingdemo
    jobs:
      - job:  
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'Hello world'
              
              echo '$(tag)'

              sh 'docker push httpd-image:$(tag)'
        
                 
          
            
       
    
    



    
     

    

