# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
  - group: myvariablesgroup
  

pool:
 name: new-agent
 vmimage: salman-007
    

steps:
- script: 
    echo myvariables-$(myvariablesgroup.name)
    echo myvariables-$(myvariablesgroup.location)
    echo myvariables-$(myvariablesgroup.designation)


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
