version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - docker --version
      - export KUBECONFIG=$HOME/.kube/config     
    finally:
      - echo succesfully docker version is $(docker --version)
      - echo kubernets version is $(kubectl version)
  pre_build:
    commands:
      - echo $Dockerpassword | docker login --username $DockerUsername --password-stdin    

  build:
    commands:
      - cd aks-purpose-project/
      - docker build -t akspurpose-repo:latest .
      - docker build -t akspurpose-repo:$CODEBUILD_BUILD_ID .
    finally:
      - echo succesfully build docker image
  post_build:
    commands:
      - docker tag akspurpose-repo:latest abidh786/akspurpose-repo:latest
      - docker tag akspurpose-repo:$CODEBUILD_BUILD_NUMBER abidh786/akspurpose-repo:$CODEBUILD_BUILD_ID
      - docker push abidh786/akspurpose-repo:latest
      - docker push abidh786/akspurpose-repo:$CODEBUILD_BUILD_ID  
