version: 0.2
phases:
  install:
    runtime-versions:
      nodejs:latest
    commands:
      - yum update -y
    finally:
      - echo succesfully system is updated

  pre_build:
    commands:
      - sudo rpm - import https://packages.microsoft.com/keys/microsoft.asc
      - sudo sh -c 'echo -e "[azure-cli]
      - name=Azure CLI
      - baseurl=https://packages.microsoft.com/yumrepos/azure-cli
      - enabled=1
      - gpgcheck=1
      - gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
      - yum install azure-cli
    finally:
      - az version          