version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - yum update -y
    finally:
      - echo succesfully system is updated

  pre_build:
    commands:
      - sh azurecli.sh
    finally:
      - az version          