version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - yum update -y
      - docker --version
      - systemctl status docker
      - systemctl start docker
      
    finally:
      - echo succesfully docker version is $(docker --version)
  pre_build:
    commands:
      - echo $Dockerpassword | docker login --username $DockerUsername --password-stdin    

  build:
    commands:
      - cd aks-purpose-project/
      - docker build -t akspurpose-repo:latest .
    finally:
      - echo succesfully build docker image
  post_build:
    commands:
      - docker tag awsekspurposerepo:latest abidh786/awsekspurposerepo:latest
      - docker push abidh786/akspurpose-repo:latest  
