version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - docker --version
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.25.7/2023-03-17/bin/darwin/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bash_profile
      - kubectl version --short --client     
    finally:
      - echo succesfully docker version is $docker --version
      - echo kubectl version $kubectl version --short --client
  pre_build:
    commands:
      - echo $Dockerpassword | docker login --username $DockerUsername --password-stdin    

  build:
    commands:
      - cd aks-purpose-project/
      - docker build -t akspurpose-repo:latest .
      - docker build -t akspurpose-repo:$CODEBUILD_BUILD_NUMBER .
    finally:
      - echo succesfully build docker image
  post_build:
    commands:
      - docker tag akspurpose-repo:latest abidh786/akspurpose-repo:latest
      - docker tag akspurpose-repo:$CODEBUILD_BUILD_NUMBER abidh786/akspurpose-repo:$CODEBUILD_BUILD_NUMBER
      - docker push abidh786/akspurpose-repo:latest
      - docker push abidh786/akspurpose-repo:$CODEBUILD_BUILD_NUMBER  
