version : 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - apt-get update -y

  build:
    commands:
      - echo this is new build number

artificats:
  files:
    - kuberenetes/*.yml
