version : 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - yum update -y

  build:
    commands:
      - echo this is new build number
      - aws s3 cp kuberenetes/ s3://newawsbucket-001.s3.ap-south-1.amazonaws.com/artificats/


