name: github actions run contionous integrated
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  aws_connect:
    name: checking iam users list
    runs-on: ubuntu-latest
    steps:
      - run: aws iam list-users
        env:
          AWS_ACCESS_KEY_ID: AKIAXUJFQFK7S7YS7XHU
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ap-south-1
        

  
          

