name: github actions demo
on:
  push:
    branches:
      - feature
  workflow_dispatch: {}
jobs:
  publish_artificats:
    name: publish artificats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir artificats
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            artificats/kuberenets/*
        
        
   
          

