name: github actions demo
on:
  push:
    branches:
      - main
      
  workflow_dispatch: {}
jobs:
  publish_artificats:
    name: publish artificats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            kuberenetes
  download_artificats:
    needs: publish_artificats
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - run: cat my-artifact/newtestfile.txt        
        
        
   
          

